<?php

namespace app\admin\controller;
use app\common\BaseController;
use think\Request;
use think\facade\Session;
use think\facade\view;

class Index extends BaseController
{
    public function initialize()
    {
        if(empty(Session::get('username'))){
            $this->redirect('admin/login/index');
        };

        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function index()
    {
        return view();
    }

    public function welcome()
    {
        return view();
    }
    public function logout()
    {
        Session::destroy();
        $this->success('退出成功','admin/login/index');
    }
}
